name: simopt
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.14
  - ruby>=2.5
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - pandas
  - seaborn
  - pillow
  - pip
  - ruff
  - joblib
  - pip:
    - mrg32k3a>=2.0
    - -e .
