name: simopt
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - numpy>=2.3.4
  - scipy>=1.16.3
  - jupyter
  - matplotlib>=3.10.7
  - pandas>=2.3.3
  - seaborn>=0.13.2
  - pillow>=12.0.0
  - pip
  - ruff>=0.14.2
  - joblib>=1.5.2
  - boltons>=25.0.0
  - cvxpy>=1.7.3
  - pydantic>=2.12.3
  - pip:
    - mrg32k3a>=2.0
    - -e .
