[build-system]
requires = ["setuptools>=77.0.3", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["simopt*"]
# Ignore the build directory so we don't circularly include built distributions.
exclude = ["build*"]

[tool.setuptools.package-data]
"simopt.data_farming" = ["*.npz"]

[project]
name = "simoptlib"
version = "1.2.2.dev0"
authors = [
  { name = "David Eckman", email = "eckman@tamu.edu" },
  { name = "Shane Henderson", email = "sgh9@cornell.edu" },
  { name = "Sara Shashaani", email = "sshasha2@ncsu.edu" },
  { name = "William Grochocinski", email = "williamgrochocinski@gmail.com" },
]
description = "A testbed for simulation-optimization experiments."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11,<3.14"
classifiers = [
  # Application Info
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Mathematics",
  # Python Versions
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  # Other Classifiers
  "Operating System :: OS Independent",
]
dependencies = [
  "boltons>=0.6.3",
  "cvxpy>=1.6.0",
  "joblib>=1.0.0",
  "matplotlib>=3.9.0",
  "mrg32k3a[rust]>=2.0.0",
  "numpy>=2.0.0",
  "pandas>=2.2.2",
  "pydantic>=2.2.0",
  "scipy>=1.13.0",
  "seaborn>=0.13.0",
]

# [project.optional-dependencies]
# TODO: convert plotting imports to lazy imports in library code
# plotting = ["matplotlib>=3.9.0", "seaborn>=0.13.0"]

# https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-groups
[dependency-groups]
all = [
  { include-group = "build" },
  { include-group = "dev" },
  { include-group = "docs" },
  { include-group = "notebooks" },
  { include-group = "testing" },
]
build = ["setuptools>=77.0.3", "build"]
dev = [
  "jupytext>=1.18.1",
  "pytest-xdist>=3.8.0",
  "pytest>=9.0.1",
  "ruff>=0.14.0",
  "ty>=0.0.1a26",
]
docs = ["sphinx>=8.0.0", "sphinx-autoapi>=3.6.0", "sphinx-rtd-theme>=3.0.0"]
notebooks = ["ipykernel>=7.1.0"]
testing = ["pyyaml"]

[project.urls]
Documentation = "https://simopt.readthedocs.io/en/latest/"
Repository = "https://github.com/simopt-admin/simopt"
Issues = "https://github.com/simopt-admin/simopt/issues"
