[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["simopt", "simopt.gui", "simopt.models", "simopt.solvers"]

[project]
name = "simoptlib"
version = "1.2.0"
authors = [
  { name = "David Eckman", email = "eckman@tamu.edu" },
  { name = "Shane Henderson", email = "sgh9@cornell.edu" },
  { name = "Sara Shashaani", email = "sshasha2@ncsu.edu" },
  { name = "William Grochocinski", email = "wagrocho@ncsu.edu" },
]
description = "A testbed for simulation-optimization experiments."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9,<3.14"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "seaborn",
    "mrg32k3a",
    "joblib>=1.5.1",
]

[project.optional-dependencies]
dev = ["sphinx"]

[project.urls]
"Homepage" = "https://github.com/simopt-admin/simopt"
"Documentation" = "https://simopt.readthedocs.io/en/latest/"
