name: "Ruff CI"

on:
  push:
    branches: [ "master", "development", "develop" ]
  pull_request:
    branches: [ "master" , "development", "develop" ]

jobs:
  linter:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ruff linting check
      uses: astral-sh/ruff-action@v2
      with:
        args: "check --no-fix"

  formatter:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ruff formatting check
      uses: astral-sh/ruff-action@v2
      with:
        args: "format --check"
